[tool.poetry]
name = "urban_heat_service"
version = "2024"
description = "Simple backend supporting the Urban Heat Map"
authors = ["Damien Allen <dev@dallen.co>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "~3.12"
fastapi = "^0.110.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
