name: Client

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./app

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: ./app

      - uses: actions/checkout@v3
        name: Commit to build branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout build
          mv ./app/dist/ ./app/build/
          git add ./app/build/
          git commit -am "Updated distributables"
          git push