name: App

on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ./app

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
          dir: ./app

      - name: Update 'build' branch
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git switch --orphan build
          mv ./app/dist/* .
          rm -rf ./app
          git add .
          git commit -am "Created distributables"
          git push --force --set-upstream origin build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Add Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync Static Files
        run: |
          rsync -avz --delete --exclude .git/ --exclude .github/ --exclude .gitignore --exclude README.md \
          -e "ssh -p ${{ secrets.SSH_PORT }}" . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/urban-heat/main
